image: node:16.17.0
pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install -g @angular/cli@14.2.1
    - npm install
    - npm run buildProd
  artifacts:
    paths:
      - public
  only:
    - master
    - pages
